In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
## loading the dataset
dataset = pd.read_csv('50_Startups.csv')
print(dataset.sample(10))

    R&D Spend  Administration  Marketing Spend       State     Profit
38   20229.59        65947.93        185265.10    New York   81229.06
10  101913.08       110594.11        229160.95     Florida  146121.95
13   91992.39       135495.07        252664.93  California  134307.35
16   78013.11       121597.55        264346.06  California  126992.93
15  114523.61       122616.84        261776.23    New York  129917.04
26   75328.87       144135.98        134050.07     Florida  105733.54
20   76253.86       113867.30        298664.47  California  118474.03
42   23640.93        96189.63        148001.11  California   71498.49
21   78389.47       153773.43        299737.29    New York  111313.02
33   55493.95       103057.49        214634.81     Florida   96778.92


In [6]:
##defining independent and dependent variables
def get_target_and_predictors(df,target):
    X = dataset.drop(target,axis=1).values
    y = dataset[target].values
    return X,y

In [7]:
X,y = get_target_and_predictors(dataset,'Profit')

In [10]:
## encoding the categorical feature
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
ct = ColumnTransformer([('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X = ct.fit_transform(X)

In [26]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [27]:
## spliting the data into tesing and traing sets
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
##normalizing features
def normalize(X):
    X[:,3:] = (X[:,3:]-np.mean(X[:,3:]))/(np.std(X[:,3:]))
    return X
X1 = X.copy()
X1 = normalize(X1)

In [30]:
print(X1.shape)

[[0.0 0.0 1.0 0.31484663762682286 0.01610715289345617 3.5324107691043833]
 [1.0 0.0 0.0 0.285955908444995 0.16814483833766472 3.2396124950898813]
 [0.0 1.0 0.0 0.18981598272180375 -0.3592912016008217 2.8619908721976524]
 [0.0 0.0 1.0 0.0945905013396793 -0.17526518420686563 2.602274399344962]
 [0.0 1.0 0.0 0.07080728347746484 -0.46170581780257675 2.423446928205021]
 [0.0 0.0 1.0 -0.03661225911782475 -0.3732650115315299 2.3887228232266255]
 [1.0 0.0 0.0 -0.00785739983809133 0.12426830995435094
  -0.0802930676421708]
 [0.0 1.0 0.0 -0.053189332172665416 0.1067458175807634 1.9793839781892926]
 [0.0 0.0 1.0 -0.15562316336057452 0.14022913845324733 1.8506184759755413]
 [1.0 0.0 0.0 -0.1263034044878982 -0.28018824860107533 1.7809859911515356]
 [0.0 1.0 0.0 -0.3512321424080438 -0.2600813930897362 0.9848695298196288]
 [1.0 0.0 0.0 -0.3642638930175841 -0.4575180008202471 1.2009971740816938]
 [0.0 1.0 0.0 -0.4357500465058678 -0.08445568464265923 1.201993518363745]
 [1.0 0.0 0.0 -0.4553993123469382