In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
## loading the dataset
dataset = pd.read_csv('50_Startups.csv')
print(dataset.sample(10))

    R&D Spend  Administration  Marketing Spend       State     Profit
38   20229.59        65947.93        185265.10    New York   81229.06
10  101913.08       110594.11        229160.95     Florida  146121.95
13   91992.39       135495.07        252664.93  California  134307.35
16   78013.11       121597.55        264346.06  California  126992.93
15  114523.61       122616.84        261776.23    New York  129917.04
26   75328.87       144135.98        134050.07     Florida  105733.54
20   76253.86       113867.30        298664.47  California  118474.03
42   23640.93        96189.63        148001.11  California   71498.49
21   78389.47       153773.43        299737.29    New York  111313.02
33   55493.95       103057.49        214634.81     Florida   96778.92


In [6]:
##defining independent and dependent variables
def get_target_and_predictors(df,target):
    X = dataset.drop(target,axis=1).values
    y = dataset[target].values
    return X,y

In [7]:
X,y = get_target_and_predictors(dataset,'Profit')

In [10]:
## encoding the categorical feature
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
ct = ColumnTransformer([('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X = ct.fit_transform(X)

In [33]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [34]:
## spliting the data into tesing and traing sets
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [44]:
##normalizing features
def normalize(X,mean,std):
    X[:,3:] = (X[:,3:]-np.mean(X[:,3:]))/(np.std(X[:,3:]))
    return X

mean = np.mean(X_train[:,3:])
std = np.std(X_train[:,3:])

X1 = X_train.copy()
X_train_norm = normalize(X1,mean=mean,std=std)
X2 = X_test.copy()
X_test_norm = normalize(X2,mean=mean,std=std)

In [45]:
print(X_train_norm)

[[0.0 1.0 0.0 -0.51715387087152 -0.17786482603415857 1.064620589913932]
 [0.0 1.0 0.0 -0.027907895690359258 -0.5422226160815743
  2.2443314128839833]
 [1.0 0.0 0.0 -1.022120774018149 -0.9489706586200827 0.5290657165258488]
 [0.0 0.0 1.0 -0.24660019015903778 0.039141500550001825
  1.6910790994059646]
 [0.0 0.0 1.0 -0.004937457938865327 -0.26557095432464284
  2.4170475406121517]
 [1.0 0.0 0.0 -0.10388425102668968 0.023726125741589207
  -0.17384446448144616]
 [0.0 1.0 0.0 -1.186174626931767 -0.6099757074287425 0.1988826222621213]
 [0.0 1.0 0.0 -1.4557009067036144 -0.29453045705995606 1.54404414155279]
 [1.0 0.0 0.0 -1.4690411973103417 -0.09565510516460696
  -1.4690411973103417]
 [0.0 0.0 1.0 -0.30763892074433713 -0.2255641787171492 1.185673489668754]
 [1.0 0.0 0.0 -0.21828242004166332 -0.3669083231082115 1.6238262714918388]
 [1.0 0.0 0.0 -0.6778977505049699 -0.23590096190518314 1.2117345474051247]
 [0.0 0.0 1.0 -0.6877255488621832 -0.46221322274227206
  -0.04344952794335668]
 [1.0 0.0 0.0

In [48]:
print(X_test_norm)

[[1.0 0.0 0.0 -0.07899949064313283 0.5586763149620206 2.2761885433613522]
 [1.0 0.0 0.0 -0.8622499128150333 -0.21107526876172494 1.1377415976080842]
 [0.0 1.0 0.0 -0.5187181798301181 0.2676532898848175 -0.09162249501888334]
 [0.0 0.0 1.0 -1.412790855491299 0.39242131371961847 -1.3995441399895097]
 [0.0 0.0 1.0 -0.03993846367876081 0.6991397251236343 2.7146095322900954]
 [0.0 0.0 1.0 -1.4195070003497803 -0.6689853614445447 -1.427452537738012]
 [0.0 1.0 0.0 -0.3232585464120553 0.6853374596411905 0.5374950558051262]
 [1.0 0.0 0.0 -0.479577118488586 0.6181610595793228 0.5948464298634701]
 [1.0 0.0 0.0 -0.4979857581509983 0.4666886716480244 -0.7519206183191418]
 [0.0 0.0 1.0 -0.16068571285146077 0.8228050042343016 -1.427452537738012]]


In [50]:
##training the model
from sklearn.linear_model import LinearRegression

In [52]:
lr = LinearRegression()
lr.fit(X_train_norm,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [53]:
##making predictions
prediction_test = lr.predict(X_test_norm)

In [54]:
print(prediction_test)

[161727.00751987 101374.01718425 122737.05696872  46081.87105485
 165175.00293731  52665.73032436 137283.63029315 124551.14053443
 120151.30712512 142549.64452467]


In [58]:
##comparing actual values and the predictions
np.set_printoptions(precision=2)
print(np.hstack((prediction_test[:,np.newaxis],y_test[:,np.newaxis])))

[[161727.01 134307.35]
 [101374.02  81005.76]
 [122737.06  99937.59]
 [ 46081.87  64926.08]
 [165175.   125370.37]
 [ 52665.73  35673.41]
 [137283.63 105733.54]
 [124551.14 107404.34]
 [120151.31  97427.84]
 [142549.64 122776.86]]


In [59]:
## training the model with the data that is not normalized
ln = LinearRegression()
ln.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [60]:
predic = ln.predict(X_test)

In [61]:
##comparing actual values and the predictions
print(np.hstack((predic[:,np.newaxis],y_test[:,np.newaxis])))

[[126362.88 134307.35]
 [ 84608.45  81005.76]
 [ 99677.49  99937.59]
 [ 46357.46  64926.08]
 [128750.48 125370.37]
 [ 50912.42  35673.41]
 [109741.35 105733.54]
 [100643.24 107404.34]
 [ 97599.28  97427.84]
 [113097.43 122776.86]]
